language: node_js

node_js:
  - "6"

notifications:
  slack: pmpkin:QReL3WOed24nwQcVtqvlQyYW

script:
- |
    if [ "$TEST_TYPE" = test ]; then
      npm test
    else
      npm run $TEST_TYPE
    fi
env:
  matrix:
    - TEST_TYPE=eslint
    - TEST_TYPE=test
